# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: StarterProject/Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install --project-directory=StarterProject
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild -workspace "StarterProject/StarterProject.xcworkspace" -scheme "RobotStore" -sdk iphonesimulator -destination 'name=iPad Retina' build 
- pod lib lint --quick
